CREATE PROC TGS_SP_IncTodoItem
    @NAME		VARCHAR (100),
    @ISCOMPLETE     VARCHAR (255)	
AS
BEGIN
	INSERT INTO TODOITEMS (NAME, ISCOMPLETE) 
	VALUES (@NAME, @ISCOMPLETE)

	SELECT SCOPE_IDENTITY()
END